[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"


[dependencies]
color-eyre = "0.6.2"
anyhow = "1.0.66"
itertools = "0.10.5"
grid = "0.9.0"
parse-display = "0.7.0"

[dev-dependencies]
rstest = "0.16.0"
